app/controllers/auth.py
from datetime import datetime

from flask import Blueprint, render_template, flash, redirect, url_for
from flask.ext.login import current_user, login_user, logout_user
from random import randint

from app.forms import MemberForm, LoginForm
from app.models import db, User


auth = Blueprint('auth', __name__)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    """Renders the register page and saves new users to the database"""
    # Makes sure logged in users cannot access the register page
    if not current_user.is_authenticated():
        form = MemberForm()
        # If the submit button is pressed
        if form.validate_on_submit():
            # Generates a username for the user composed of their real name and a random number
            username = form.name.data.lower().replace(' ', '') + str(randint(1, 10))
            # Creates a User object with the data they typed in
            user = User(name=form.name.data, username=username, email=form.email.data, password=form.password.data,
                        dob=form.dob.data, distance=form.distance.data, charity_event=form.charity_event.data,
                        phone=form.phone.data, weight=form.weight.data, joined=datetime.now())
            # Saves the user to the database
            db.session.add(user)
            db.session.commit()
            print('%s has been registered.' % user.name)
            # Returns the user to the login page with a message
            flash('You can now login!', 'success')
            return redirect(url_for('auth.login'))
        # If there were validation errors, re-render the view and show them
        for error in form.errors.items():
            flash(error[1][0], 'warning')
        return render_template('auth/register.html', form=form)
    return redirect(url_for('main.home'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Renders the login page and logs in the user"""
    if not current_user.is_authenticated():
        form = LoginForm()
        if form.validate_on_submit():
            # Query that returns the first user with the entered email address.
            user = User.query.filter_by(email=form.email.data).first()
            # Checks that a user was returned and that the password is correct.
            if user is not None and user.check_password(form.password.data):
                # If so, log them in and redirect them to the home page
                login_user(user, form.remember.data)
                return redirect(url_for('main.home'))
            flash('Invalid email address or password.', 'warning')
        # If there were validation errors, re-render the view and show them
        for error in form.errors.items():
            flash(error[1][0], 'warning')
        return render_template('auth/login.html', form=form)
    return redirect(url_for('main.home'))


@auth.route('/logout')
def logout():
    """Logs the user out of the system"""
    logout_user()
    return redirect(url_for('main.home'))

app/controllers/main.py
from datetime import datetime
from calendar import month_name
from random import randint

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask.ext.login import current_user, login_required, logout_user
from flask.ext.sqlalchemy import *
import re

from app.models import User, Activity, db
from app.helpers import validation_error, update_user
from app.performance_data import performance_data

main = Blueprint('main', __name__)

current_date = datetime.now().date()


@main.route('/')
@login_required
def home():
    return redirect(url_for('main.performance', month=current_date.strftime('%B').lower()))


@main.route('/profiles/<username>', methods=['GET', 'POST'])
@login_required
def profiles(username):
    # If the user has attempted to change their profile
    if request.method == 'POST':
        user = User.query.filter_by(id=current_user.get_id()).first()

        # If the user tries to change their name
        if request.form.get('name'):
            only_letters = re.compile(r'^[A-Za-z\-" "]*$')
            if only_letters.match(request.form.get('name')):
                user.name = request.form.get('name').title()
                user.username = request.form.get('name').lower().replace(' ', '').replace('-', '') + str(randint(1, 10))
                update_user(user, 'name', False)
                return redirect(url_for('main.profiles', username=user.username))
            else:
                validation_error('Your name may only contain letters and dashes.')

        # If the user tries to change their email
        elif request.form.get('email'):
            valid_email = re.compile(r'^.+@[^.].*\.[a-z]{2,10}$')
            if valid_email.match(request.form.get('email')):
                user.email = request.form.get('email')
                update_user(user, 'email')
            else:
                validation_error('You must enter a valid email.')

        # If the user tries to change their phone number
        elif request.form.get('phone'):
            valid_phone = re.compile(
                r'^\s*\(?(020[78]\)? ?[1-9][0-9]{2} ?[0-9]{4})|(0[1-8][0-9]{3}\)? ?[1-9][0-9]{2} ?[0-9]{3})\s*$')
            if valid_phone.match(request.form.get('phone')):
                user.phone = request.form.get('phone')
                update_user(user, 'phone number')
            else:
                validation_error('You must enter a valid UK phone number.')

        # If the user tries to change their dob
        elif request.form.get('dob'):
            user.dob = request.form.get('dob')
            update_user(user, 'date of birth')

        # If the user tries to change their weight
        elif request.form.get('weight'):
            check_integer = re.compile(r'^-?[0-9]+$')
            if not check_integer.match(request.form.get('weight')):
                validation_error('You must enter a number.')
            elif not 10 <= int(request.form.get('weight')) <= 100:
                validation_error('Your weight must be between 10kg - 100kg.')
            else:
                user.weight = request.form.get('weight')
                update_user(user, 'weight')

        # If the user attempts to delete their account
        elif request.form.get('delete'):
            if request.form.get('delete') != 'I will lose everything':
                validation_error('You must type in the message exactly!')
            else:
                user_id = current_user.get_id()
                logout_user()
                User.query.filter_by(id=user_id).delete()  # Deletes the user's record
                Activity.query.filter_by(user_id=user_id).delete()  # Deletes all the user's activities
                db.session.commit()
                flash('Your account was successfully deleted - sorry to see you go!', 'success')
                return redirect(url_for('auth.login'))

    possible_user = User.query.filter_by(username=username).first_or_404()
    if current_user.username == possible_user.username:
        activity_number = len(Activity.query.filter_by(user_id=current_user.get_id()).all())
        total_users = len(User.query.all())
        return render_template('profiles/own_profile.html', current_user=current_user, activity_number=activity_number, total_users=total_users)

    # If the user is not the profile they attempted to access, 403 
    abort(403)


@main.route('/add-training', methods=['GET', 'POST'])
@login_required
def add_training():
    """Returns add activity page; returns all the training sessions done on current day"""
    activities = Activity.query.filter_by(user_id=current_user.get_id(), date=current_date).all()
    total_calories = 0
    total_hours = 0
    for activity in activities:
        total_calories += activity.calories
        total_hours += activity.hours
    return render_template('training/add_training.html', date=current_date, current_user=current_user, activities=activities,
                           total_calories=total_calories, total_hours=total_hours)


@main.route('/performance/<month>', methods=['GET', 'POST'])
@login_required
def performance(month):
    months = [month_name[x].lower() for x in range(1, 13)]
    all_activities = Activity.query.filter_by(user_id=current_user.get_id()).all()
    available_months = []

    # Calculates all the months that the user has done activities in
    for activity in all_activities:
        for x in range(1, 13):
            if activity.date.month == x and months[x - 1] not in available_months:
                available_months.append(months[x - 1])

    if month.lower() in available_months:
        user_data = performance_data(month.lower())
        return render_template('performance/user_performance.html', user_data=user_data,
                                current_month=month.title(), months=available_months)
    # If they haven't done any training in that month, 404
    return redirect(url_for('main.add_training'))


@main.route('/performance/compare/<username>', methods=['GET', 'POST'])
@login_required
def compare_performance(username):
    """Builds the dropdown list for comparison page and returns the comparison data"""

    if User.query.filter_by(username=username).first():
        users = User.query.filter_by(charity_event=0).filter(User.id != current_user.id).all()
        user_list = sorted([[user.username, user.name] for user in users])
        comparison_id = User.query.filter_by(username=username).first().id
        comparison_name = User.query.filter_by(username=username).first().name.split(' ', 1)[0]

        # Creates a large dictionary with all the user's activities and the comparison's activities
        activities = {
            'runs': {
                'user': Activity.query.filter_by(user_id=current_user.get_id(), sport='running').all(),
                'comparison': Activity.query.filter_by(user_id=comparison_id, sport='running').all()
            },
            'cycles': {
                'user': Activity.query.filter_by(user_id=current_user.get_id(), sport='cycling').all(),
                'comparison': Activity.query.filter_by(user_id=comparison_id, sport='cycling').all()
            },
            'swims': {
                'user': Activity.query.filter_by(user_id=current_user.get_id(), sport='swimming').all(),
                'comparison': Activity.query.filter_by(user_id=comparison_id, sport='swimming').all()
            }
        }

        # Adds up all the user's running activities
        user_run_calories = 0
        user_run_hours = 0
        for run in activities['runs']['user']:
            user_run_calories += run.calories
            user_run_hours += run.hours

        # Adds up all the user's cycling activities
        user_cycle_calories = 0
        user_cycle_hours = 0
        for cycle in activities['cycles']['user']:
            user_cycle_calories += cycle.calories
            user_cycle_hours += cycle.hours

        # Adds up all the user's running activities
        user_swim_calories = 0
        user_swim_hours = 0
        for swim in activities['swims']['user']:
            user_swim_calories += swim.calories
            user_swim_hours += swim.hours

        user_calorie_total = user_run_calories + user_cycle_calories + user_swim_calories
        user_hour_total = user_run_hours + user_cycle_hours + user_swim_hours

        # Adds up all the comparison's running activities
        comparison_run_calories = 0
        comparison_run_hours = 0
        for run in activities['runs']['comparison']:
            comparison_run_calories += run.calories
            comparison_run_hours += run.hours

        # Adds up all the comparison's cycling activities
        comparison_cycle_calories = 0
        comparison_cycle_hours = 0
        for cycle in activities['cycles']['comparison']:
            comparison_cycle_calories += cycle.calories
            comparison_cycle_hours += cycle.hours

        # Adds up all the comparison's running activities
        comparison_swim_calories = 0
        comparison_swim_hours = 0
        for swim in activities['swims']['comparison']:
            comparison_swim_calories += swim.calories
            comparison_swim_hours += swim.hours

        # Adds up all the data
        comparison_calorie_total = comparison_run_calories + comparison_cycle_calories + comparison_swim_calories
        comparison_hour_total = comparison_run_hours + comparison_cycle_hours + comparison_swim_hours

        # Creates a big long dictionary which contains all the data for both the logged in and the comparison user
        user_data = {
            'user': {
                'calories': {
                    'running': user_run_calories, 'swimming': user_swim_calories, 'cycling': user_cycle_calories,
                    'total': user_calorie_total
                },
                'hours': {
                    'running': user_run_hours, 'swimming': user_swim_hours, 'cycling': user_cycle_hours,
                    'total': user_hour_total

app/templates/layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/readable/bootstrap.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/css/datepicker.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.3/compressed/themes/classic.css"/>
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.3/compressed/themes/classic.time.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    <title>{% block title %} - Parkwood Vale Harriers{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target="#main_nav" type="button">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Parkwood Vale Harriers</a>
        </div>
        <div class="collapse navbar-collapse" id="main_nav">
            {% if current_user.is_authenticated() %}
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.home') }}">My Performance</a></li>
                    <li><a href="{{ url_for('main.add_training') }}">Add Training Session</a></li>
                    <li><a href="{{ url_for('main.compare_performance', username='alice8') }}">Compare Performance</a></li>
                    <li><a href="{{ url_for('main.rankings') }}">Charity Team Rankings</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ current_user.name }}<span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url_for('main.profiles', username=current_user.username) }}">Your
                                Profile</a></li>
                            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/js/bootstrap-datepicker.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.3/compressed/picker.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.3/compressed/picker.time.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1/Chart.min.js"></script>
<script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js"></script>
{% block scripts %}{% endblock %}
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</html>